var configParameters = {
    RESOURCE_ID : 0,
    CPU:1,
    CPU_UTIL:3,
    DISKEPHEMERALSIZE:4,
    DISKROOTSIZE:5,
    DISKWRITEBYTES:6,
    DISKWRITEREQUESTS:7,
    INSTANCE:8,
    MEMORY:9,
    VCPUS:10,
    NETWORKINCOMINGBYTES:11,
    NETWORKOUTGOINGBYTES:12
};

module.exports = configParameters;